//let score ="33abc"
//console.log( typeof score)
//console.log(score)
//let valueInNumber = Number(score)
//console.log(typeof valueInNumber )
//console.log(score)
/*let key ="kartik"
let booleankey =Boolean(key)
console.log(key)
console.log(booleankey)
// 1 =true,0= false,"" =false,"kartik" = true
let numbber =33
let stringnubber =String(numbber)
console.log(stringnubber)
console.log(typeof stringnubber)
console.log(1+2)
console.log("1"+2)
console.log(1+"2")
console.log(1+2+"3")
console.log("1"+2+3)
//console.log( +true)
//console.log(true+)
console.log(+"")
console.log("2" == 2)
console.log("2" === 2)
console.log(null<0)
console.log(null == 0)
console.log(null >= 0)
console.log(undefined<0)
console.log(undefined > 0)
console.log(undefined == 0)
const id = Symbol("234")
const anotherid = Symbol("234")
console.log(id === anotherid)*/
console.log(2+3)
console.log(2-3)
let num =4
let valueofnum = String(num)
console.log(valueofnum)
console.log(typeof valueofnum)
console.log(1+2+"3")
console.log("1"+"2"+3)