let mydate = new Date(2023-09-18)
console.log(mydate.toLocaleString())
console.log(mydate.toDateString())
let myTimestamp = Date.now()
console.log(myTimestamp)
console.log(mydate.getTime())
console.log(Math.floor((Date.now()/1000)))
